# Generated by Django 3.2.4 on 2021-06-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='curso',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='rg',
            field=models.CharField(max_length=9, unique=True, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='codigo_curso',
            field=models.CharField(max_length=10, verbose_name='Código do Curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descricao',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('B', 'Básico'), ('I', 'Intermediário'), ('A', 'Avançado')], default='B', max_length=1, verbose_name='Nível'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='periodo',
            field=models.CharField(choices=[('M', 'Matutino'), ('V', 'Vespertino'), ('N', 'Noturno')], default='M', max_length=1, verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='alt1_correta',
            field=models.CharField(max_length=255, verbose_name='Alternativa A (correta)'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='alt2_errada',
            field=models.CharField(max_length=255, verbose_name='Alternativa B'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='alt3_errada',
            field=models.CharField(max_length=255, verbose_name='Alternativa C'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='alt4_errada',
            field=models.CharField(max_length=255, verbose_name='Alternativa D'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='alt5_errada',
            field=models.CharField(max_length=255, verbose_name='Alternativa E'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='questao',
            field=models.CharField(max_length=255, verbose_name='Questão'),
        ),
        migrations.AlterField(
            model_name='prova',
            name='descricao_prova',
            field=models.CharField(max_length=255, verbose_name='Descrição da Prova'),
        ),
    ]
