# Generated by Django 3.2.4 on 2021-06-30 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_auto_20210630_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pergunta',
            name='prova',
        ),
        migrations.AddField(
            model_name='pergunta',
            name='prova',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='escola.prova'),
        ),
    ]
