# Generated by Django 3.2.4 on 2021-06-30 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_auto_20210630_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='prova',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.prova'),
        ),
    ]
