# Generated by Django 3.2.4 on 2021-06-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0004_alter_pergunta_prova'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pergunta',
            name='prova',
        ),
        migrations.AddField(
            model_name='pergunta',
            name='prova',
            field=models.ManyToManyField(to='escola.Prova'),
        ),
    ]
