# Generated by Django 3.2.4 on 2021-06-30 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0005_auto_20210630_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pergunta',
            name='prova',
        ),
        migrations.AddField(
            model_name='pergunta',
            name='prova',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='escola.prova'),
        ),
    ]
