# Generated by Django 3.2.4 on 2021-06-30 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0007_alter_pergunta_prova'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pergunta',
            name='prova',
        ),
    ]
