# Generated by Django 3.2.4 on 2021-06-30 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0008_remove_pergunta_prova'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerguntasProva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.prova')),
                ('questao', models.ManyToManyField(to='escola.Pergunta')),
            ],
        ),
    ]
