# Generated by Django 3.2.4 on 2021-06-30 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0011_auto_20210630_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pergunta',
            name='prova',
        ),
        migrations.CreateModel(
            name='ModeloProva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.prova')),
                ('questoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.pergunta')),
            ],
        ),
    ]
