# Generated by Django 3.2.4 on 2021-06-30 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0012_auto_20210630_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeloprova',
            name='prova',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='escola.prova'),
        ),
        migrations.AlterField(
            model_name='modeloprova',
            name='questoes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='escola.pergunta'),
        ),
    ]
