# Generated by Django 3.2.4 on 2021-06-30 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0013_auto_20210630_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeloprova',
            name='prova',
        ),
    ]
