# Generated by Django 3.2.4 on 2021-06-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0014_remove_modeloprova_prova'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloprova',
            name='prova',
            field=models.ManyToManyField(to='escola.Prova'),
        ),
        migrations.RemoveField(
            model_name='modeloprova',
            name='questoes',
        ),
        migrations.AddField(
            model_name='modeloprova',
            name='questoes',
            field=models.ManyToManyField(to='escola.Pergunta'),
        ),
    ]
