# Generated by Django 3.2.4 on 2021-07-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0015_auto_20210630_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='modeloprova',
            name='questoes',
            field=models.ManyToManyField(to='escola.Pergunta', verbose_name='Questões'),
        ),
    ]
